### ISSUE TITLE
Deprecated Node version on Flutter Install Task

### ISSUE THREAD

**Issue by LucasRohr** [hey24sheep/azure-flutter-tasks#124]
Hey, I'm currently working on a Flutter project using Azure Pipelines and the Flutter Install Task created on this repo and it was working as usual until a couple of days ago.

It happens that the used Node version of the Install task (version 10) is considered deprecated now and should be updated to Node 20. The fact that version 10 is deprecated now makes all pipelines with the Flutter Install Task fail, as you can see in the logs bellow.

Could you please update the Node version to avoid pipeline breaks?
Thanks in advance.

```
##[warning]Task 'Flutter Install Task' version 0 (FlutterInstall@0) is dependent on a Node version (10) that is end-of-life. Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance: https://aka.ms/node-runner-guidance
##[error]Object reference not set to an instance of an object.
##[debug]System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.CheckIfTaskNodeRunnerIsDeprecated(IExecutionContext executionContext, TaskStepDefinitionReference task) in /Users/runner/work/1/s/src/Agent.Worker/TaskManager.cs:line 382
   at Microsoft.VisualStudio.Services.Agent.Worker.TaskManager.DownloadAsync(IExecutionContext executionContext, IEnumerable`1 steps) in /Users/runner/work/1/s/src/Agent.Worker/TaskManager.cs:line 100
   at Microsoft.VisualStudio.Services.Agent.Worker.JobExtension.InitializeJob(IExecutionContext jobContext, AgentJobRequestMessage message) in /Users/runner/work/1/s/src/Agent.Worker/JobExtension.cs:line 140
```

**Comment by LucasRohr** [comment]
I was just doing some research on the repo and I found out that the Flutter Build Task (which I also use) is using Node 10 as well, so I think all tasks with Node 10 should be updated to Node 20, not only the Install Task.

**Comment by hey24sheep** [comment]
@LucasRohr thanks for opening this issue. Please give me sometime and I will try to do it ASAP

**Comment by hey24sheep** [comment]
@LucasRohr, I have updated the version from **0.3.18** to **0.4.0** to denote major changes. If previous version of this extension is needed then you download it from [releases](https://github.com/hey24sheep/azure-flutter-tasks/releases/tag/0.3.18_node10). 

Please let me know if everything works fine by closing this issue, thanks

**Comment by hey24sheep** [comment]
Released new version **0.4.1**
