### ISSUE TITLE
Self-hosted agent unable to build flutter project

### ISSUE THREAD

**Issue by attiqeurrehman** [hey24sheep/azure-flutter-tasks#131]
Hi,

I have the following pipeline that is running on the self-hosted agent: 

 ```yaml
jobs:
  - job: Android
    pool: 'Self-hosted Agent Pool'
    steps:
    - checkout: self
      fetchDepth: 0
    - task: SonarCloudPrepare@3
      inputs:
        SonarQube: 'SonarQube Cloud'
        organization: 'jet-clean'
        scannerMode: 'cli'
        configMode: 'file'
    - task: FlutterInstall@0
      inputs:
        mode: 'auto'
        channel: 'stable'
        version: 'latest'
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: '.'
        verboseMode: true
        debugMode: true
    - task: FlutterTest@0
      inputs:
        projectDirectory: '.'
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
    - task: SonarCloudAnalyze@3
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    - task: SonarCloudPublish@3
      inputs:
        pollingTimeoutSec: '300'
```

but it is failing with the following error:

```
2024-12-17T21:14:14.3891878Z [  +98 ms] [!] No Android SDK found. Try setting the ANDROID_HOME environment variable.
2024-12-17T21:14:14.4036156Z [  +14 ms] 
2024-12-17T21:14:14.4113861Z            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
2024-12-17T21:14:14.4118010Z            #1      exitWithNoSdkMessage (package:flutter_tools/src/android/gradle_utils.dart:816:3)
2024-12-17T21:14:14.4121806Z            #2      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:133:7)
2024-12-17T21:14:14.4125488Z            #3      FlutterCommand.verifyThenRunCommand (package:flutter_tools/src/runner/flutter_command.dart:1815:12)
2024-12-17T21:14:14.4150518Z            <asynchronous suspension>
2024-12-17T21:14:14.4151268Z            #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1450:27)
2024-12-17T21:14:14.4152462Z            <asynchronous suspension>
2024-12-17T21:14:14.4153075Z            #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
2024-12-17T21:14:14.4153526Z            <asynchronous suspension>
2024-12-17T21:14:14.4153882Z            #6      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
2024-12-17T21:14:14.4154235Z            <asynchronous suspension>
2024-12-17T21:14:14.4154633Z            #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:421:9)
2024-12-17T21:14:14.4155025Z            <asynchronous suspension>
2024-12-17T21:14:14.4155380Z            #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
2024-12-17T21:14:14.4155719Z            <asynchronous suspension>
2024-12-17T21:14:14.4156095Z            #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:364:5)
2024-12-17T21:14:14.4156469Z            <asynchronous suspension>
2024-12-17T21:14:14.4156833Z            #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:131:9)
2024-12-17T21:14:14.4157186Z            <asynchronous suspension>
2024-12-17T21:14:14.4157538Z            #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:153:19)
2024-12-17T21:14:14.4157878Z            <asynchronous suspension>
2024-12-17T21:14:14.4158177Z            #12     main (package:flutter_tools/executable.dart:94:3)
2024-12-17T21:14:14.4158476Z            <asynchronous suspension>
2024-12-17T21:14:14.4158600Z 
2024-12-17T21:14:14.4158678Z 
2024-12-17T21:14:14.6101064Z [ +207 ms] ensureAnalyticsSent: 203ms
2024-12-17T21:14:14.6102699Z [        ] Running 1 shutdown hook
2024-12-17T21:14:14.6105257Z [        ] Shutdown hooks complete
2024-12-17T21:14:14.6247438Z [  +12 ms] exiting with code 1
```

and even though ANDROID_HOME environment variable is set that points to the `C:\Users\username\AppData\Local\Android\Sdk`.

**Comment by hey24sheep** [comment]
Hi, I don't think this has anything to do with this extension. It's an issue with your configuration. You should open up a stackoverflow issue.

Go through these
- https://stackoverflow.com/questions/73160436/azure-devops-sdk-location-not-found-define-location-with-an-android-sdk-root
- https://stackoverflow.com/questions/27620262/sdk-location-not-found-define-location-with-sdk-dir-in-the-local-properties-fil

**Comment by hey24sheep** [comment]
Hi, is this fixed?
