### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by Stewioie** [hey24sheep/azure-flutter-tasks#40]
Using your extension to build iOS is failed.
```
                   /bin/sh -c /Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Uphome/IntermediateBuildFilesPath/Runner.build/Uphome_Release-iphoneos/uphome.build/Script-19E93AE727EB319C000FDED8.sh
               ♦ /Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/bin/flutter --verbose assemble --no-version-check --output=/Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Uphome/BuildProductsPath/Uphome_Release-iphoneos/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode_13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= -dCodesignIdentity=A9B11C1A5E23D1A9E0F41E5A44B1E5DD3B48B33F release_ios_bundle_flutter_assets
               Unhandled exception:
               ProcessException: No such file or directory
                 Command: /Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/bin/flutter --verbose assemble --no-version-check --output=/Users/runner/Library/Developer/Xcode/DerivedData/Runner-gsjhxdjmxuzkkbgjdidjocbaqrkc/Build/Intermediates.noindex/ArchiveIntermediates/Uphome/BuildProductsPath/Uphome_Release-iphoneos/ -dTargetPlatform=ios -dTargetFile=lib/main.dart -dBuildMode=release -dIosArchs=arm64 -dSdkRoot=/Applications/Xcode_13.3.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk -dSplitDebugInfo= -dTreeShakeIcons=false -dTrackWidgetCreation=false -dDartObfuscation=false -dEnableBitcode= --ExtraGenSnapshotOptions= --DartDefines= --ExtraFrontEndOptions= -dCodesignIdentity=A9B11C1A5E23D1A9E0F41E5A44B1E5DD3B48B33F release_ios_bundle_flutter_assets
               #0      _ProcessImpl._runAndWait (dart:io-patch/process_patch.dart:487:7)
               #1      _runNonInteractiveProcessSync (dart:io-patch/process_patch.dart:632:18)
               #2      Process.runSync (dart:io-patch/process_patch.dart:68:12)
               #3      Context.runSync (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:92:42)
               #4      Context.buildApp (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:449:34)
               #5      Context.run (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:51:9)
               #6      main (file:///Users/runner/hostedtoolcache/Flutter/3.0.0-stable/macos/flutter/packages/flutter_tools/bin/xcode_backend.dart:17:5)
               #7      _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:32)
               #8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
               Command PhaseScriptExecution failed with a nonzero exit code
```
On local mac the project can be archived.

Task hiearchy:
FlutterInstall
InstallAppleCertificate
InstallAppleProvisioningProfile
CocoaPods
FlutterBuild

Ive attached the full verbose log of your Task.
[log.txt](https://github.com/hey24sheep/azure-flutter-tasks/files/8741139/log.txt)

**Comment by hey24sheep** [comment]
Hi, I have not faced this issue before. I am confused as to what the real issue is. Only thing it shows is wrong file or directory which again could be either "Output" or "dSdkRoot" path.

Could you give these a read and try solutions from these, I apologize as I am unable to help much in this.

- [link 1](https://stackoverflow.com/questions/69698881/command-phasescriptexecution-failed-with-a-nonzero-exit-code-using-cocoapods)
- [link 2](https://stackoverflow.com/questions/57919267/command-phasescriptexecution-failed-with-a-nonzero-exit-code-while-trying-to-add)
- [link 3](https://github.com/hey24sheep/azure-flutter-tasks/issues/35)

**Comment by Stewioie** [comment]
FLUTTER_APPLICATION_PATH can be problem?
in build settings it's set to "/Users/Work/XXXXX"

**Comment by Stewioie** [comment]
yeah it was the problem. Finally solved. Thanks for the assist

**Comment by hey24sheep** [comment]
I'm glad you got it fixed
