### ISSUE TITLE
Custom urls in FlutterInstall task don't work

### ISSUE THREAD

**Issue by ko16a46** [hey24sheep/azure-flutter-tasks#46]
Hello,

I tried using custom urls to get around #43, but unfortunately it seems that custom urls simply don't work as expected. The `FlutterInstall` task fails (logs attached in next comment).

The root cause is that the `cacheDir` function in the Azure pipeline tools lib (called [here](https://github.com/hey24sheep/azure-flutter-tasks/blob/524a4d3fb9b17aac137c623b0f7e78ef33d83de7/tasks/install/index.ts#L95)) expects a semver compliant version for the version spec.

However, when using custom urls, the task just naively gets the last part of the url path and uses that as the version (seen [here](https://github.com/hey24sheep/azure-flutter-tasks/blob/524a4d3fb9b17aac137c623b0f7e78ef33d83de7/tasks/install/index.ts#L32))

Because of the wrong version format, the `cacheDir` function fails which causes the whole task to fail. It could be fixed by writing a more robust way to extract the version from the url. Alternatively, we could add a `customUrlVersion` input to let us explicitly set the version for custom urls.

**Comment by ko16a46** [comment]
Logs attached. I removed the repetitive unzipping logs
```

##[debug]testing directory '/Users/runner/work/_temp'
##[debug]mkdir '/Users/runner/work/_temp/155d21e4-5d70-49cf-9bf0-0c2df8f4c647'
##[debug]which 'unzip'
##[debug]found: '/usr/bin/unzip'
##[debug]/usr/bin/unzip arg: /Users/runner/work/_temp/a24fd750-f719-4251-b71f-e530cc9a74b0
##[debug]exec tool: /usr/bin/unzip
##[debug]arguments:
##[debug]   /Users/runner/work/_temp/a24fd750-f719-4251-b71f-e530cc9a74b0
/usr/bin/unzip /Users/runner/work/_temp/a24fd750-f719-4251-b71f-e530cc9a74b0
Archive:  /Users/runner/work/_temp/a24fd750-f719-4251-b71f-e530cc9a74b0
   creating: flutter/
  inflating: flutter/CODE_OF_CONDUCT.md  
  inflating: flutter/.ci.yaml        
  inflating: flutter/LICENSE         
   creating: flutter/bin/
   creating: flutter/bin/cache/
  inflating: flutter/bin/cache/openssl.stamp  
...

  flutter/bin/cache/artifacts/engine/darwin-x64/FlutterMacOS.framework/FlutterMacOS -> Versions/Current/FlutterMacOS
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Resources -> Versions/Current/Resources
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Versions/Current -> A
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Headers -> Versions/Current/Headers
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/Modules -> Versions/Current/Modules
  flutter/bin/cache/artifacts/engine/darwin-x64-release/FlutterMacOS.framework/FlutterMacOS -> Versions/Current/FlutterMacOS
(node:2049) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'trim' of null
##[debug]Exit code 0 received from tool '/usr/bin/unzip'
##[debug]STDIO streams have closed for tool '/usr/bin/unzip'
    at Function.clean (/Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/node_modules/semver/semver.js:285:25)
##[debug]Extracted to '/Users/runner/work/_temp/155d21e4-5d70-49cf-9bf0-0c2df8f4c647' 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.0.2-stable.zip' archive
    at _createToolPath (/Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/node_modules/azure-pipelines-tool-lib/tool.js:249:62)
##[debug]Adding '/Users/runner/work/_temp/155d21e4-5d70-49cf-9bf0-0c2df8f4c647' to cache (Flutter,flutter_macos_3.0.2-stable.zip, macos)
    at Object.<anonymous> (/Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/node_modules/azure-pipelines-tool-lib/tool.js:281:24)
Caching tool: Flutter null macos
    at Generator.next (<anonymous>)
##[debug]source dir: /Users/runner/work/_temp/155d21e4-5d70-49cf-9bf0-0c2df8f4c647
    at /Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/node_modules/azure-pipelines-tool-lib/tool.js:7:71
##[debug]Agent.Version=2.204.0
    at new Promise (<anonymous>)
##[debug]Agent.ToolsDirectory=/Users/runner/hostedtoolcache
    at __awaiter (/Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/node_modules/azure-pipelines-tool-lib/tool.js:3:12)
##[debug]Trying again to get (Flutter,flutter_macos_3.0.2-stable.zip, macos) tool from local cache
    at Object.cacheDir (/Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/node_modules/azure-pipelines-tool-lib/tool.js:272:12)
##[debug]isExplicit: null
    at /Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/index.js:94:14
##[debug]explicit? false
    at Generator.next (<anonymous>)
##[debug]Agent.Version=2.204.0
    at fulfilled (/Users/runner/work/_tasks/FlutterInstall_83c91e05-bdf9-42ce-b27e-6dae8771294e/0.3.0/index.js:5:58)
##[debug]Agent.ToolsDirectory=/Users/runner/hostedtoolcache
    at process._tickCallback (internal/process/next_tick.js:68:7)
##[debug]evaluating 0 versions
(node:2049) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
##[debug]match not found
(node:2049) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
##[debug]task result: Failed
```

Note the line `Caching tool: Flutter null macos`. The version is null because `semver.clean` is called on the version, and `semver.clean` returns `null` if the string is invalid semver. This `null` version eventually leads to the crash

**Comment by hey24sheep** [comment]
Custom urls work as intentded. You have not written what and how you used it, so I can't debug your config.

Custom version exsits too, you can use it as shown in the image.
![Capture](https://user-images.githubusercontent.com/31468022/173819617-2749cbf9-949a-44a7-b10d-3e0d32401f56.PNG)

To use the "customUrl" you can use it like this:
Example : https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.0.2-stable.zip
![Capture](https://user-images.githubusercontent.com/31468022/173819977-cb857119-7f38-4e35-bb96-732d0506af0b.PNG)

Now your question regarding, semversion. If you check this [line](https://github.com/hey24sheep/azure-flutter-tasks/blob/524a4d3fb9b17aac137c623b0f7e78ef33d83de7/tasks/install/index.ts#L32) you will see how version is handled in the customURL case. If you check this [semver code](https://github.com/npm/node-semver/blob/main/functions/parse.js). You will see why it throws "NULL". 

Now, How do I know custom urls work? First, I have these setup on my Windows agent. 
Second, How can you test if these work? 
- Fork this repo
- do  npm install
- Dir to "tasks" => "install"
- run tsc in "install" directory
- open another cmd in "tests" folder within "install"
- open "latest.ts" and replace/append the below lines
- `
runner.setInput("mode", "custom");
runner.setInput("customUrl", "https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.0.2-stable.zip");
`
- save and run tsc in this folder too
- run "node latest" and you will see the output of CMD.

**Comment by ko16a46** [comment]
Apologies, I didn't post a sample yml. 

I tested on my repo, this sample azure-pipeline.yml on a Flutter project is enough for the pipeline to fail on my end:

```yaml
# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: macos-latest

steps:
- task: FlutterInstall@0
  displayName: 'Install Flutter SDK'
  inputs:
    mode: 'Custom'
    customUrl: 'https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.0.2-stable.zip'
```

**Comment by hey24sheep** [comment]
@ko16a46 It is working on windows as well as on my local tests. I think semver is a little strict or works different on mac vms. But in either case just to be future safe I have added a small fragment parser on the url to parse the version out of it. So, it should work for you now. Let me know if it is working by closing this issue.

**Comment by hey24sheep** [comment]
Glad to hear that 👍🏻
