### ISSUE TITLE
Run flutter analyse from SonarQube plugin

### ISSUE THREAD

**Issue by ElaineBSchwaner** [hey24sheep/azure-flutter-tasks#64]
Hello! Thanks for making this plugin available.

I have a problem integrating my pipeline with SonarQube
Inside SonarQubeAnalyze@5 step, it is necessary to run flutter analyse - it is automatically done by SonarQube plugin. So I can not use Flutter command from this plugin.
It is breaking in this step because it does not find flutter

**How can I set flutter in the environment path, so it could run 'flutter analyze' in SonarQubeAnalyze@5 step?**

Here is my yml:

`pool:
  vmImage: macOS-latest

resources:
  - repo: self

variables:
  - group: driveb-mobile

stages:
  - stage: Android
    jobs:
      - job:
        steps:
          - task: SonarQubePrepare@5
            inputs:
              SonarQube: 'DriveB-App-SonarQube'
              scannerMode: 'CLI'
              configMode: 'manual'
              cliProjectKey: 'driver-app'

          - task: FlutterInstall@0
            displayName: Installing Flutter SDK
            inputs:
              mode: 'auto'
              channel: 'stable'
              version: 'custom'
              customVersion: '3.0.5'

          - task: FlutterBuild@0
            displayName: Building APK
            inputs:
              target: 'apk'
              projectDirectory: '$(root)'
              buildFlavour: $(buildConfiguration)
              entryPoint: 'lib/run/main_$(buildConfiguration).dart'

          - task: SonarQubeAnalyze@5

          - task: SonarQubePublish@5
            inputs:
              pollingTimeoutSec: '300'`

`

Error in the step SonarQubeAnalyze@5:

`

	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:189)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:138)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: org.buildobjects.process.StartupException: Could not startup process 'flutter analyze'.
	at org.buildobjects.process.Proc.<init>(Proc.java:91)
	at org.buildobjects.process.ProcBuilder.run(ProcBuilder.java:205)
	at fr.insideapp.sonarqube.dart.lang.issues.dartanalyzer.DartAnalyzerSensor.getIssuesFromAnalyzer(DartAnalyzerSensor.java:130)
	... 32 common frames omitted
Caused by: java.io.IOException: Cannot run program "flutter": error=2, No such file or directory

`

**Comment by hey24sheep** [comment]
Hi, I have personally never used Sonar. In my opinion, Flutter has its own Analyser and it should be used always. As sonar will do the same.

But, read this [Article](https://blogs.infosupport.com/flutter-sonarqube-with-azure-pipelines/). It might help you in setup. Let me know if it does.

**Comment by hey24sheep** [comment]
@ElaineBSchwaner Hi, I have updated the extension which should fix this issue. #73 This issue is similar as this one. So, I am closing this issue in regards to that. Feel free to re-open or file a new issue in case of any issue, thank you.
